step_0_exceptions:
  ΑΚΟΥΣΤΙΚΩΝ: ΑΚΟΥΣΤΙΚΑ
  ΕΝΟΣ: ΕΝΑ
  ΒΕΡΜΟΥΔΕΣ: ΒΕΡΜΟΥΔ
  ΚΡΕΜΑΣ: ΚΡΕΜΑ
  ΚΡΕΜΕΣ: ΚΡΕΜΑ
  ΛΑΒΑΣ: ΛΑΒΑ
  ΛΑΔΟΥΣΑ: ΛΑΔΟΥΣ
  ΛΙΒΑΝΗΣ: ΛΙΒΑΝΗ
  ΜΑΤΙΑ: ΜΑΤΙ
  ΜΑΤΙΟΥ: ΜΑΤΙ
  ΜΑΤΙΩΝ: ΜΑΤΙ
  ΠΑΤΑΚΗΣ: ΠΑΤΑΚΗ
  ΠΟΔΙΑ: ΠΟΔΙ
  ΠΟΔΙΟΥ: ΠΟΔΙ
  ΠΟΔΙΩΝ: ΠΟΔΙ
  ΡΟΛΟΓΙΑ: ΡΟΛ
  ΣΚΙ: ΣΚ
  ΤΑΜΠΟΥΡΑ: ΤΑΜΠΟΥΡΟ
step_1_exceptions:
  ΑΓΟΡΙΑ: ΑΓΟΡΙ
  ΑΓΟΡΙΩΝ: ΑΓΟΡΙ
  ΒΙΟΛΑΣ: ΒΙΟΛΑ
  ΒΙΟΛΕΣ: ΒΙΟΛΑ
  ΦΑΓΙΑ: ΦΑ
  ΦΑΓΙΟΥ: ΦΑ
  ΦΑΓΙΩΝ: ΦΑ
  ΣΚΑΓΙΑ: ΣΚΑ
  ΣΚΑΓΙΟΥ: ΣΚΑ
  ΣΚΑΓΙΩΝ: ΣΚΑ
  #ΟΛΟΓΙΟΥ: ΟΛΟ
  #ΟΛΟΓΙΑ: ΟΛΟ
  #ΟΛΟΓΙΩΝ: ΟΛΟ
  ΣΟΓΙΟΥ: ΣΟ
  ΣΟΓΙΑ: ΣΟ
  ΣΟΓΙΩΝ: ΣΟ
  ΤΑΤΟΓΙΑ: ΤΑΤΟ
  ΤΑΤΟΓΙΟΥ: ΤΑΤΟ
  ΤΑΤΟΓΙΩΝ: ΤΑΤΟ
  ΚΡΕΑΣ: ΚΡΕ
  ΚΡΕΑΤΟΣ: ΚΡΕ
  ΚΡΕΑΤΑ: ΚΡΕ
  ΚΡΕΑΤΩΝ: ΚΡΕ
  ΝΤΟΥΛΑΠΑΣ: ΝΤΟΥΛΑΠΑ
  ΝΤΟΥΛΑΠΩΝ: ΝΤΟΥΛΑΠΑ
  ΝΤΟΥΛΑΠΕΣ: ΝΤΟΥΛΑΠΑ
  ΜΠΑΧΑΡΙΚΟ: ΜΠΑΧΑΡΙΚ
  ΜΠΑΧΑΡΙΚΩΝ: ΜΠΑΧΑΡΙΚ
  ΜΠΑΧΑΡΙΚΑ: ΜΠΑΧΑΡΙΚ
  ΠΑΙΔΙΚΑ: ΠΑΙΔΙΚ
  ΠΑΙΔΙΚΗ: ΠΑΙΔΙΚ
  ΠΑΙΔΙΚΟ: ΠΑΙΔΙΚ
  ΠΑΙΔΙΚΟΣ: ΠΑΙΔΙΚ
  ΠΑΙΔΙΚΩΝ: ΠΑΙΔΙΚ
  ΠΑΙΔΙΚΕΣ: ΠΑΙΔΙΚ
  ΠΑΝΤΕΛΟΝΕΣ: ΠΑΝΤΕΛΟΝΑ
  ΠΕΡΑΣ: ΠΕΡ
  ΠΕΡΑΤΟΣ: ΠΕΡ
  ΠΕΡΑΤΑ: ΠΕΡ
  ΠΕΡΑΤΩΝ: ΠΕΡ
  ΤΕΡΑΣ: ΤΕΡ
  ΤΕΡΑΤΟΣ: ΤΕΡ
  ΤΕΡΑΤΑ: ΤΕΡ
  ΤΕΡΑΤΩΝ: ΤΕΡ
  ΦΩΣ: ΦΩ
  ΦΩΤΟΣ: ΦΩ
  ΦΩΤΑ: ΦΩ
  ΦΩΤΩΝ: ΦΩ
  ΦΩΤΟ: ΦΩ
  ΧΑΡΤΕΣ: ΧΑΡΤΗ
  ΧΑΡΤΩΝ: ΧΑΡΤΗ
  ΧΑΡΤΗΣ: ΧΑΡΤΗ
  ΚΑΘΕΣΤΩΣ: ΚΑΘΕΣΤ
  ΚΑΘΕΣΤΩΤΟΣ: ΚΑΘΕΣΤ
  ΚΑΘΕΣΤΩΤΑ: ΚΑΘΕΣΤ
  ΚΑΘΕΣΤΩΤΩΝ: ΚΑΘΕΣΤ
  ΓΕΓΟΝΟΣ: ΓΕΓΟΝ
  ΓΕΓΟΝΟΤΟΣ: ΓΕΓΟΝ
  ΓΕΓΟΝΟΤΑ: ΓΕΓΟΝ
  ΓΕΓΟΝΟΤΩΝ: ΓΕΓΟΝ
  ΕΥΑ: ΕΥ

protected_words:
  - ΘΑΛΑΣΣΗΣ
  - ΑΓΟΡΙ
  - ΑΚΟΥΣΤΙΚΑ
  - ΑΚΡΙΒΩΣ
  - ΑΛΑ
  - ΑΛΛΑ
  - ΑΛΛΙΩΣ
  - ΑΛΛΟΤΕ
  - ΑΜΑ
  - ΑΝΩ
  - ΑΝΑ
  - ΑΝΑΜΕΣΑ
  - ΑΝΑΜΕΤΑΞΥ
  - ΑΝΕΥ
  - ΑΝΤΙ
  - ΑΝΤΙΠΕΡΑ
  - ΑΝΤΙΟ
  - ΑΞΑΦΝΑ
  - ΑΠΟ
  - ΑΠΟΨΕ
  - ΑΡΑ
  - ΑΡΑΓΕ
  - ΑΡΚΑΣ
  - ΑΥΡΙΟ
  - ΑΦΟΙ
  - ΑΦΟΥ
  - ΑΦΟΤΟΥ
  - ΒΙΟΛΑ
  - ΒΙΟΛΟΓΟΣ
  - ΒΡΕ
  - ΓΑΖΙ
  - ΓΕΙΑ
  - ΓΙΑ
  - ΓΙΑΤΙ
  - ΓΡΑΜΜΑ
  - ΔΕΗ
  - ΔΕΝ
  - ΔΕΡΜΑΤΙΝΗ
  - ΔΗΛΑΔΗ
  - ΔΙΧΩΣ
  - ΔΥΟ
  - ΕΑΝ
  - ΕΓΩ
  - ΕΔΩ
  - ΕΔΑ
  - ΕΙΘΕ
  - ΕΙΜΑΙ
  - ΕΙΜΑΣΤΕ
  - ΕΙΣΑΙ
  - ΕΙΣΑΣΤΕ
  - ΕΙΝΑΙ
  - ΕΙΣΤΕ
  - ΕΙΤΕ
  - ΕΚΕΙ
  - ΕΚΟ
  - ΕΛΑ
  - ΕΜΑΣ
  - ΕΜΕΙΣ
  - ΕΝΑ
  - ΕΝΤΕΛΩΣ
  - ΕΝΤΟΣ
  - ΕΝΤΩΜΕΤΑΞΥ
  - ΕΝΩ
  - ΕΞΙ
  - ΕΞΙΣΟΥ
  - ΕΞΗΣ
  - ΕΞΩ
  - ΕΟΚ
  - ΕΠΑΝΩ
  - ΕΠΕΙΔΗ
  - ΕΠΕΙΤΑ
  - ΕΠΙ
  - ΕΠΙΣΗΣ
  - ΕΠΟΜΕΝΩΣ
  - ΕΠΤΑ
  - ΕΣΑΣ
  - ΕΣΕΙΣ
  - ΕΣΤΩ
  - ΕΣΥ
  - ΕΣΩ
  - ΕΤΣΙ
  - ΕΥΓΕ
  - ΕΦΕ
  - ΕΦΕΞΗΣ
  - ΕΧΤΕΣ
  - ΕΩΣ
  - ΗΔΗ
  - ΗΜΙ
  - ΗΠΑ
  - ΗΤΟΙ
  - ΘΕΡΜΟΣ
  - ΘΕΣ
  - ΙΔΙΩΣ
  - ΙΔΗ
  - ΙΚΑ
  - ΙΣΩΣ
  - ΚΑΘΕ
  - ΚΑΘΕΤΙ
  - ΚΑΘΟΛΟΥ
  - ΚΑΘΩΣ
  - ΚΑΙ
  - ΚΑΝ
  - ΚΑΝΟ
  - ΚΑΠΟΤΕ
  - ΚΑΠΟΥ
  - ΚΑΡΑΤΕ
  - ΚΑΤΑ
  - ΚΑΤΙ
  - ΚΑΤΟΠΙΝ
  - ΚΑΤΩ
  - ΚΕΙ
  - ΚΙΧ
  - ΚΚΕ
  - ΚΟΛΑΝ
  - ΚΥΡΙΩΣ
  - ΚΡΕΜΑ
  - ΚΩΣ
  - ΛΑΒΑ
  - ΛΙΒΑΝΗ
  - ΜΑΓΙΟ
  - ΜΑΓΙΩ
  - ΜΑΚΑΡΙ
  - ΜΑΚΡΑΜΕ
  - ΜΑΛΙΣΤΑ
  - ΜΑΛΛΟΝ
  - ΜΑΙ
  - ΜΑΟ
  - ΜΑΟΥΣ
  - ΜΑΣ
  - ΜΑΤΙ
  - ΜΕΘΑΥΡΙΟ
  - ΜΕΣ
  - ΜΕΣΑ
  - ΜΕΤΑ
  - ΜΕΤΑΞΥ
  - ΜΕΧΡΙ
  - ΜΗΔΕ
  - ΜΗΝ
  - ΜΗΠΩΣ
  - ΜΗΤΕ
  - ΜΙΑ
  - ΜΙΑΣ
  - ΜΙΣ
  - ΜΜΕ
  - ΜΟΛΟΝΟΤΙ
  - ΜΟΥ
  - ΜΠΑ
  - ΜΠΑΜΠΟΥ
  - ΜΠΑΣ
  - ΜΠΕΡΙ
  - ΜΠΕΤΟΝΙ
  - ΜΠΟΥΦΑΝ
  - ΜΠΡΟΣ
  - ΝΑΙ
  - ΝΕΣ
  - ΝΤΑ
  - ΝΤΕ
  - ΝΤΟΥΛΑΠΑ
  - ΞΑΝΑ
  - ΟΗΕ
  - ΟΚΤΩ
  - ΟΜΩΣ
  - ΟΝΕ
  - ΟΠΑ
  - ΟΠΟΥ
  - ΟΠΩΣ
  - ΟΣΟ
  - ΟΤΑΝ
  - ΟΤΕ
  - ΟΤΙ
  - ΟΥΤΕ
  - ΟΧΙ
  - ΠΑΛΙ
  - ΠΑΝ
  - ΠΑΝΟ
  - ΠΑΝΤΕΛΟΝΑ
  - ΠΑΝΤΟΤΕ
  - ΠΑΝΤΟΥ
  - ΠΑΝΤΩΣ
  - ΠΑΝΩ
  - ΠΑΡΑ
  - ΠΑΝΙ
  - ΠΕΡΑ
  - ΠΕΡΙ
  - ΠΕΡΛΕ
  - ΠΕΡΙΠΟΥ
  - ΠΑΤΑΚΗ
  - ΠΕΤΑΛΟ
  - ΠΙΑ
  - ΠΙΟ
  - ΠΙΣΩ
  - ΠΛΑΙ
  - ΠΛΕΟΝ
  - ΠΛΗΝ
  - ΠΟΔΙ
  - ΠΟΤΕ
  - ΠΟΥ
  - ΠΡΟ
  - ΠΡΟΣ
  - ΠΡΟΧΤΕΣ
  - ΠΡΟΧΘΕΣ
  - ΡΟΔΙ
  - ΡΟΛΑ
  - ΡΟΥΤΕΡ
  - ΠΩΣ
  - ΣΑΙ
  - ΣΑΣ
  - ΣΑΝ
  - ΣΕΙΣ
  - ΣΙΑ
  - ΣΟΙ
  - ΣΟΥ
  - ΣΡΙ
  - ΣΤΡΑΤΑ
  - ΣΤΥΛΟ
  - ΣΥΝ
  - ΣΥΝΑΜΑ
  - ΣΧΕΔΟΝ
  - ΤΑΔΕ
  - ΤΑΜΠΟΥΡΕ
  - ΤΑΜΠΟΥΡΟ
  - ΤΑΞΙ
  - ΤΑΧΑ
  - ΤΕΙ
  - ΤΗΝ
  - ΤΗΣ
  - ΤΙΠΟΤΑ
  - ΤΙΠΟΤΕ
  - ΤΙΣ
  - ΤΟΝ
  - ΤΟΤΕ
  - ΤΟΥ
  - ΤΟΥΣ
  - ΤΣΑ
  - ΤΣΕ
  - ΤΣΙ
  - ΤΣΟΥ
  - ΤΩΝ
  - ΥΠΟ
  - ΥΠΟΨΗ
  - ΥΠΟΨΙΝ
  - ΥΣΤΕΡΑ
  - ΦΕΤΟΣ
  - ΦΙΣ
  - ΦΛΟΤΕΡ
  - ΦΠΑ
  - ΦΤΕΡΗ
  - ΧΑΡΤΗ
  - ΧΑΦ
  - ΧΘΕΣ
  - ΧΤΕΣ
  - ΧΩΡΙΣ
  - ΩΣ
  - ΩΣΑΝ
  - ΩΣΟΤΟΥ
  - ΩΣΠΟΥ
  - ΩΣΤΕ
  - ΩΣΤΟΣΟ
