step_1_exceptions:
  ΦΑΓΙΑ: ΦΑ
  ΦΑΓΙΟΥ: ΦΑ
  ΦΑΓΙΩΝ: ΦΑ
  ΣΚΑΓΙΑ: ΣΚΑ
  ΣΚΑΓΙΟΥ: ΣΚΑ
  ΣΚΑΓΙΩΝ: ΣΚΑ
  #ΟΛΟΓΙΟΥ: ΟΛΟ
  #ΟΛΟΓΙΑ: ΟΛΟ
  #ΟΛΟΓΙΩΝ: ΟΛΟ
  ΣΟΓΙΟΥ: ΣΟ
  ΣΟΓΙΑ: ΣΟ
  ΣΟΓΙΩΝ: ΣΟ
  ΤΑΤΟΓΙΑ: ΤΑΤΟ
  ΤΑΤΟΓΙΟΥ: ΤΑΤΟ
  ΤΑΤΟΓΙΩΝ: ΤΑΤΟ
  ΚΡΕΑΣ: ΚΡΕ
  ΚΡΕΑΤΟΣ: ΚΡΕ
  ΚΡΕΑΤΑ: ΚΡΕ
  ΚΡΕΑΤΩΝ: ΚΡΕ
  ΠΕΡΑΣ: ΠΕΡ
  ΠΕΡΑΤΟΣ: ΠΕΡ
  ΠΕΡΑΤΑ: ΠΕΡ
  ΠΕΡΑΤΩΝ: ΠΕΡ
  ΤΕΡΑΣ: ΤΕΡ
  ΤΕΡΑΤΟΣ: ΤΕΡ
  ΤΕΡΑΤΑ: ΤΕΡ
  ΤΕΡΑΤΩΝ: ΤΕΡ
  ΦΩΣ: ΦΩ
  ΦΩΤΟΣ: ΦΩ
  ΦΩΤΑ: ΦΩ
  ΦΩΤΩΝ: ΦΩ
  ΚΑΘΕΣΤΩΣ: ΚΑΘΕΣΤ
  ΚΑΘΕΣΤΩΤΟΣ: ΚΑΘΕΣΤ
  ΚΑΘΕΣΤΩΤΑ: ΚΑΘΕΣΤ
  ΚΑΘΕΣΤΩΤΩΝ: ΚΑΘΕΣΤ
  ΓΕΓΟΝΟΣ: ΓΕΓΟΝ
  ΓΕΓΟΝΟΤΟΣ: ΓΕΓΟΝ
  ΓΕΓΟΝΟΤΑ: ΓΕΓΟΝ
  ΓΕΓΟΝΟΤΩΝ: ΓΕΓΟΝ

protected_words:
  - ΑΚΡΙΒΩΣ
  - ΑΛΑ
  - ΑΛΛΑ
  - ΑΛΛΙΩΣ
  - ΑΛΛΟΤΕ
  - ΑΜΑ
  - ΑΝΩ
  - ΑΝΑ
  - ΑΝΑΜΕΣΑ
  - ΑΝΑΜΕΤΑΞΥ
  - ΑΝΕΥ
  - ΑΝΤΙ
  - ΑΝΤΙΠΕΡΑ
  - ΑΝΤΙΟ
  - ΑΞΑΦΝΑ
  - ΑΠΟ
  - ΑΠΟΨΕ
  - ΑΡΑ
  - ΑΡΑΓΕ
  - ΑΥΡΙΟ
  - ΑΦΟΙ
  - ΑΦΟΥ
  - ΑΦΟΤΟΥ
  - ΒΡΕ
  - ΓΕΙΑ
  - ΓΙΑ
  - ΓΙΑΤΙ
  - ΓΡΑΜΜΑ
  - ΔΕΗ
  - ΔΕΝ
  - ΔΗΛΑΔΗ
  - ΔΙΧΩΣ
  - ΔΥΟ
  - ΕΑΝ
  - ΕΓΩ
  - ΕΔΩ
  - ΕΔΑ
  - ΕΙΘΕ
  - ΕΙΜΑΙ
  - ΕΙΜΑΣΤΕ
  - ΕΙΣΑΙ
  - ΕΙΣΑΣΤΕ
  - ΕΙΝΑΙ
  - ΕΙΣΤΕ
  - ΕΙΤΕ
  - ΕΚΕΙ
  - ΕΚΟ
  - ΕΛΑ
  - ΕΜΑΣ
  - ΕΜΕΙΣ
  - ΕΝΤΕΛΩΣ
  - ΕΝΤΟΣ
  - ΕΝΤΩΜΕΤΑΞΥ
  - ΕΝΩ
  - ΕΞΙ
  - ΕΞΙΣΟΥ
  - ΕΞΗΣ
  - ΕΞΩ
  - ΕΟΚ
  - ΕΠΑΝΩ
  - ΕΠΕΙΔΗ
  - ΕΠΕΙΤΑ
  - ΕΠΙ
  - ΕΠΙΣΗΣ
  - ΕΠΟΜΕΝΩΣ
  - ΕΠΤΑ
  - ΕΣΑΣ
  - ΕΣΕΙΣ
  - ΕΣΤΩ
  - ΕΣΥ
  - ΕΣΩ
  - ΕΤΣΙ
  - ΕΥΓΕ
  - ΕΦΕ
  - ΕΦΕΞΗΣ
  - ΕΧΤΕΣ
  - ΕΩΣ
  - ΗΔΗ
  - ΗΜΙ
  - ΗΠΑ
  - ΗΤΟΙ
  - ΘΕΣ
  - ΙΔΙΩΣ
  - ΙΔΗ
  - ΙΚΑ
  - ΙΣΩΣ
  - ΚΑΘΕ
  - ΚΑΘΕΤΙ
  - ΚΑΘΟΛΟΥ
  - ΚΑΘΩΣ
  - ΚΑΙ
  - ΚΑΝ
  - ΚΑΠΟΤΕ
  - ΚΑΠΟΥ
  - ΚΑΤΑ
  - ΚΑΤΙ
  - ΚΑΤΟΠΙΝ
  - ΚΑΤΩ
  - ΚΕΙ
  - ΚΙΧ
  - ΚΚΕ
  - ΚΟΛΑΝ
  - ΚΥΡΙΩΣ
  - ΚΩΣ
  - ΜΑΚΑΡΙ
  - ΜΑΛΙΣΤΑ
  - ΜΑΛΛΟΝ
  - ΜΑΙ
  - ΜΑΟ
  - ΜΑΟΥΣ
  - ΜΑΣ
  - ΜΕΘΑΥΡΙΟ
  - ΜΕΣ
  - ΜΕΣΑ
  - ΜΕΤΑ
  - ΜΕΤΑΞΥ
  - ΜΕΧΡΙ
  - ΜΗΔΕ
  - ΜΗΝ
  - ΜΗΠΩΣ
  - ΜΗΤΕ
  - ΜΙΑ
  - ΜΙΑΣ
  - ΜΙΣ
  - ΜΜΕ
  - ΜΟΛΟΝΟΤΙ
  - ΜΟΥ
  - ΜΠΑ
  - ΜΠΑΣ
  - ΜΠΟΥΦΑΝ
  - ΜΠΡΟΣ
  - ΝΑΙ
  - ΝΕΣ
  - ΝΤΑ
  - ΝΤΕ
  - ΞΑΝΑ
  - ΟΗΕ
  - ΟΚΤΩ
  - ΟΜΩΣ
  - ΟΝΕ
  - ΟΠΑ
  - ΟΠΟΥ
  - ΟΠΩΣ
  - ΟΣΟ
  - ΟΤΑΝ
  - ΟΤΕ
  - ΟΤΙ
  - ΟΥΤΕ
  - ΟΧΙ
  - ΠΑΛΙ
  - ΠΑΝ
  - ΠΑΝΟ
  - ΠΑΝΤΟΤΕ
  - ΠΑΝΤΟΥ
  - ΠΑΝΤΩΣ
  - ΠΑΝΩ
  - ΠΑΡΑ
  - ΠΕΡΑ
  - ΠΕΡΙ
  - ΠΕΡΙΠΟΥ
  - ΠΙΑ
  - ΠΙΟ
  - ΠΙΣΩ
  - ΠΛΑΙ
  - ΠΛΕΟΝ
  - ΠΛΗΝ
  - ΠΟΤΕ
  - ΠΟΥ
  - ΠΡΟ
  - ΠΡΟΣ
  - ΠΡΟΧΤΕΣ
  - ΠΡΟΧΘΕΣ
  - ΡΟΔΙ
  - ΠΩΣ
  - ΣΑΙ
  - ΣΑΣ
  - ΣΑΝ
  - ΣΕΙΣ
  - ΣΙΑ
  - ΣΚΙ
  - ΣΟΙ
  - ΣΟΥ
  - ΣΡΙ
  - ΣΥΝ
  - ΣΥΝΑΜΑ
  - ΣΧΕΔΟΝ
  - ΤΑΔΕ
  - ΤΑΞΙ
  - ΤΑΧΑ
  - ΤΕΙ
  - ΤΗΝ
  - ΤΗΣ
  - ΤΙΠΟΤΑ
  - ΤΙΠΟΤΕ
  - ΤΙΣ
  - ΤΟΝ
  - ΤΟΤΕ
  - ΤΟΥ
  - ΤΟΥΣ
  - ΤΣΑ
  - ΤΣΕ
  - ΤΣΙ
  - ΤΣΟΥ
  - ΤΩΝ
  - ΥΠΟ
  - ΥΠΟΨΗ
  - ΥΠΟΨΙΝ
  - ΥΣΤΕΡΑ
  - ΦΕΤΟΣ
  - ΦΙΣ
  - ΦΠΑ
  - ΧΑΦ
  - ΧΘΕΣ
  - ΧΤΕΣ
  - ΧΩΡΙΣ
  - ΩΣ
  - ΩΣΑΝ
  - ΩΣΟΤΟΥ
  - ΩΣΠΟΥ
  - ΩΣΤΕ
  - ΩΣΤΟΣΟ
